### ISSUE TITLE
Polar Bear Spawn randomly in Caves

### ISSUE THREAD

**Issue by MonoAdrian23** [Nukkit-coders/MobPlugin#249] opened 2021-10-02 07:41 UTC
### Info

This is:
- [x] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
 Polar Bear Spawn Randomly in Caves.

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment] 2022-01-02 23:44
Duplicate of #78

**Closed by PetteriM1** 2022-01-02 23:44 UTC
