### ISSUE TITLE
Mobs and server chat freezes every 20-30 min

### ISSUE THREAD

**Issue by MasterLuke117** [Nukkit-coders/MobPlugin#88] opened 2018-08-30 10:26 UTC
only when the mob-plugin is enabled,  every 20-30 min the mobs will freeze and chat messages in game stop updating, no error messages are generated, and on multiple servers, relogging fixes the issue for another 20-30 min.
this has been a problem for weeks and even with the latest nukkitx and mob plugin build(as of today).

with mob plugin removed the problem does not happen.
One of the Nukkit Devs worked on this issue and was unable to resolve it and recommended i put in a issue request here.

Client: Win 10 and IOS

config-version: 2

entities:
  auto-spawn-tick: 200
  worlds-spawn-disabled: "exampleworld1,exampleworld2"
  despawn-entities: true
  despawn-ticks: 12000

max-spawns:
  bat: 2
  blaze: 1
  chicken: 4
  cow: 2
  creeper: 1
  enderman: 1
  ghast: 0
  husk: 0
  horse: 1
  mooshroom: 0
  ocelot: 1
  pig: 1
  polarbear: 1
  rabbit: 3
  stray: 0
  sheep: 3
  skeleton: 1
  spider: 1
  wolf: 1
  zombie: 2

**Comment by PetteriM1** [comment] 2018-08-30 12:00
One question: have you tested does the game freeze just for you or for all players?

**Comment by MasterLuke117** [comment] 2018-08-31 00:27
Hi!!

This happens to everyone, chat stops showing, the game doesn’t freeze per se but it’s common for chunks to stop loading,if you run a command like /home when your lagged out you stay in place and after you relog your at the sethome location then

if you ask Suprememortal, he tried to fix it and determined it was a problem on the plugin end.

Thanks for all the great work!

Luke

**Comment by PetteriM1** [comment] 2018-08-31 06:07
Yeah bug came after 1.5 and I still havent found the reason.
The weird thing is I have this bug happened even I have been playing bedwars where is no mobs or animals.

**Comment by CheeseyAlpaca** [comment] 2018-09-12 22:45
Confirmed this is happening to all users. No problems at first, and then after 20 minutes or so, the issue starts. Logging out, and logging back in, resolves, but very frustrating for players. Thanks!

**Comment by PetteriM1** [comment] 2018-09-16 12:51
This happens also without mob plugin if many entities moves same time, weird

**Comment by zzz1999** [comment] 2018-09-16 13:11
Mobs spawn very

**Comment by zzz1999** [comment] 2018-09-16 13:11
Mobs spawn very frequently

**Comment by PetteriM1** [comment] 2018-09-27 15:01
Should now happen not (so) often, noticed that despawning was broken (fixed in latest build) and there were more mobs than should be

**Comment by SupremeMortal** [comment] 2018-09-27 19:49
Might be something to do with the new movement mechanics introduced. Maybe try the EntityDeltaPacket

**Comment by PetteriM1** [comment] 2018-10-20 17:48
@SupremeMortal How should I use MoveEntityDeltaPacket?

**Comment by PetteriM1** [comment] 2019-01-05 09:44
Does this still happen? Haven't got this issue with 1.8

**Comment by MasterLuke117** [comment] 2019-01-07 12:05
yes, it does, on 1.8 and with the 1.5.9 ver plugin

**Comment by whoatemycookie8297** [comment] 2019-01-10 15:57
Haven't experienced the issue yet.

**Comment by jrodr10** [comment] 2019-02-24 13:39
This happens V 1.7.1 for minecraft 1.9.0

**Comment by PetteriM1** [comment] 2019-02-24 13:41
> This happens V 1.7.1 for minecraft 1.9.0

Yea the solution is if someone figures out how to use MoveEntityDeltaPacket

**Comment by AlicanCopur** [comment] 2019-07-20 14:53
This happens V1.9.0.5 for Minecraft 1.11

**Comment by PetteriM1** [comment] 2019-07-20 15:08
https://github.com/NukkitX/Nukkit/issues/703

**Comment by Htepple** [comment] 2019-07-20 15:14
This happens V1.9.0.5 for Minecraft 1.12.0

**Comment by DueKay** [comment] 2019-08-01 12:07
Hallo PetteriM1,

leider habe ich das Problem auch seid kurzem. Wenn ich es richtig einschätze, müsste es seid dem letzten update vom MobPlugin der Fall sein.
Es scheint so als würde kein Tier mehr despawnen und dadurch fliegt man relativ schnell raus. Das merkt man dann sobald man keine Chat nachrichten mehr rein bekommt. Und bei mir verschwindet dann auch die Anzeige der BossRollBar und des Xhud Plugins. Dann bringt nur noch ein rejoin was.
Seid wenigen Wochen ist unser Server für User offen, wodurch ich mich natürlich über eine schnelle Lösung freuen würde.
Die Despawnticks in der config stehen auf 6000, so wie es immer war.

MfG DueKay

---------------------------------------------------------


Hello PetteriM1,

Unfortunately I have the problem also recently. If I judge correctly, it would have to be the case for the last MobPlugin update.
It seems like no animal despawnen more and thereby flies out relatively quickly. You will notice that as soon as you do not get a chat anymore. And with me disappears then also the announcement of the BossRollBar and the Xhud Plugins. Then only a rejoin brings something.
Within a few weeks, our server is open to users, of course I would be happy about a quick solution.
The despawnticks in the configuration are set to 6000, which is how it always was.

MfG DueKay

**Comment by PetteriM1** [comment] 2019-08-01 13:45
> Hallo PetteriM1,
> 
> leider habe ich das Problem auch seid kurzem. Wenn ich es richtig einschätze, müsste es seid dem letzten update vom MobPlugin der Fall sein.
> Es scheint so als würde kein Tier mehr despawnen und dadurch fliegt man relativ schnell raus. Das merkt man dann sobald man keine Chat nachrichten mehr rein bekommt. Und bei mir verschwindet dann auch die Anzeige der BossRollBar und des Xhud Plugins. Dann bringt nur noch ein rejoin was.
> Seid wenigen Wochen ist unser Server für User offen, wodurch ich mich natürlich über eine schnelle Lösung freuen würde.
> Die Despawnticks in der config stehen auf 6000, so wie es immer war.
> 
> MfG DueKay
> 
> Hello PetteriM1,
> 
> Unfortunately I have the problem also recently. If I judge correctly, it would have to be the case for the last MobPlugin update.
> It seems like no animal despawnen more and thereby flies out relatively quickly. You will notice that as soon as you do not get a chat anymore. And with me disappears then also the announcement of the BossRollBar and the Xhud Plugins. Then only a rejoin brings something.
> Within a few weeks, our server is open to users, of course I would be happy about a quick solution.
> The despawnticks in the configuration are set to 6000, which is how it always was.
> 
> MfG DueKay

Despawning should be fixed in 1.9.2.3 but it doesn't fix the actual issue

**Comment by SupremeMortal** [comment] 2019-08-01 21:11
@PetteriM1 Did the new raknet code in Nukkit have any affect on this issue?

**Comment by PetteriM1** [comment] 2019-08-01 21:26
> @PetteriM1 Did the new raknet code in Nukkit have any effect on this issue?

I don't think so

**Comment by TheGuw** [comment] 2020-06-04 04:54
The problem is still occurring. Nukkit and Mob-plugin in the latest version 1.12.1 ...

It looks like something synchronized, if another player joined 5 minutes after me, when the error occurs for me, 5 minutes later it occurs with the other player...

**Comment by PetteriM1** [comment] 2020-12-30 20:03
Closing this if nobody have had this issue since plugin version 1.15.0

**Closed by PetteriM1** 2020-12-30 20:03 UTC
Labels: confirmed, nukkit bug, wontfix
