### ISSUE TITLE
Animals cannot be farmed/enter through gate

### ISSUE THREAD

**Issue by bubbleshoot9** [Nukkit-coders/MobPlugin#221] opened 2021-05-17 18:16 UTC
### Info

This is:
- [X ] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
Summary: 
Animals cannot be farmed/mated, they cannot also enter/exit through a gate. 
If you force entry by removing the gate then sealing them inside, they disappear overnight. 

Steps to replicate: 
Fence off an area with a gate.
Lure cows in with hay for example

Actual Result: 
They do not enter through the gate.
IF you force entry and feed them, they do not mate.
IF you leave it overnight, they disappear

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
![image](https://user-images.githubusercontent.com/81651687/118536680-eeadee00-b743-11eb-931a-35fd144426ac.png)


```
Config:
```
version: 0
LoadOnStart: true
UseOwnGamemode: false
Gamemode: 0
playerlimit: 10
movementcheck: true
protected: false
note: ''

```

**Comment by PetteriM1** [comment] 2021-05-17 18:20
Breeding is not implemented on the public version yet

**Comment by PetteriM1** [comment] 2021-05-17 18:31
Duplicate of #100

**Closed by PetteriM1** 2021-05-17 18:31 UTC
Labels: enhancement
