### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by ipad54** [Nukkit-coders/MobPlugin#185] opened 2020-06-26 13:42 UTC
### Info

This is:
- [ ] bug report
- [X ] feature request
- [ ] other

### Your issue / suggestion

Please, make sure that the wither can break obsidian

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by Htepple** [comment] 2020-06-26 13:43
He can't #104

**Comment by PetteriM1** [comment] 2020-06-26 14:16
Duplicate of #104

**Closed by PetteriM1** 2020-06-26 14:16 UTC
