### ISSUE TITLE
Mob dont make baby

### ISSUE THREAD

**Issue by Doxestic** [Nukkit-coders/MobPlugin#237] opened 2021-07-10 15:39 UTC
### Info

This is:
- [X] bug report
- [x] feature request
- [ ] other

### Your issue / suggestion

When feed 2 cow or chiken or other mobs they dont try to make baby
Using last version of mob plugin
### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment] 2021-07-27 13:55
Not implemented yet. Duplicate of #100

**Closed by PetteriM1** 2021-07-27 13:55 UTC
