### ISSUE TITLE
Add lead and only endermans spawns in the end

### ISSUE THREAD

**Issue by IrineuMC** [Nukkit-coders/MobPlugin#188] opened 2020-07-25 13:47 UTC
### Info
This is:
- [X] bug report
- [X] feature request
- [ ] other

### Issue
* There is no way to pull the mobs with the noose (or lead).
* In the end, generating other types of monsters that should not be born, I think the main thing would be that the endermans spawn automatically and not spawn others mobs.

### Suggestion
* Being able to add noose to all entities that can be leash knot.
* Add an option in "config.yml" in relation to the end. Example:
```
# enable or disable enderman spawn in the end
the_end: true
```

**Comment by PetteriM1** [comment] 2020-07-25 14:05
One report/feature request per issue please

**Comment by PetteriM1** [comment] 2020-07-31 16:06
Duplicate of #57 and #158

**Closed by PetteriM1** 2020-07-31 16:06 UTC
Labels: enhancement
