### ISSUE TITLE
Wither bug

### ISSUE THREAD

**Issue by ipad54** [Nukkit-coders/MobPlugin#156] opened 2020-05-21 07:46 UTC
### Info

This is:
- [X] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion

Wither can’t break obsidian 

### Configuration

```
Config: Default

**Comment by PetteriM1** [comment] 2020-05-21 08:59
Duplicate of #104

**Closed** 2020-05-21 09:00 UTC
